// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: infra, app, target, pipeline.branch
//
// The project definition. Every file projen owns -- package.json, tsconfig.json,
// cdk.json, .gitignore, .projen/ -- is derived from this one and is regenerated by
// `npx projen`. Edit this file, never those.
//
// Placeholders the generator substitutes:
//   APP_NAME  CDK_VERSION  DEFAULT_BRANCH

import { awscdk } from 'projen';
import { NodePackageManager } from 'projen/lib/javascript';

const project = new awscdk.AwsCdkTypeScriptApp({
  name: 'testing-ecs-truly-auto-mode-infra',
  defaultReleaseBranch: 'main',

  // The floor for aws-cdk-lib. Kept equal to the version the non-projen template
  // pins, so the two styles synthesize the same templates from the same sources.
  cdkVersion: '2.263.0',

  projenrcTs: true,

  // The pipeline runs `npm ci` against a committed package-lock.json. Projen's
  // default is yarn, which would leave no lockfile for that step to install from.
  packageManager: NodePackageManager.NPM,

  // src/main.ts instantiates both stacks. Projen resolves this against srcdir and
  // writes the matching `app` command into cdk.json.
  appEntrypoint: 'main.ts',

  // The stack sources are written by the skill; a projen sample would collide.
  sampleCode: false,

  // Projen writes workflows relative to this project, which is the infra/
  // subdirectory. GitHub only reads .github at the repository root, so those files
  // would never run -- dead workflows that look live. The deploy pipeline is
  // generated separately, at the root, by Phase 4.
  github: false,

  // No tests are generated, and a jest task with no test files fails the build.
  jest: false,

  // The stack sources are generated, not hand-written, so lint findings are noise
  // that nobody can act on without editing a file the skill owns.
  eslint: false,

  licensed: false,

  // The same context flags the non-projen template sets in cdk.json.
  context: {
    '@aws-cdk/aws-lambda:recognizeLayerVersion': true,
    '@aws-cdk/core:checkSecretUsage': true,
    '@aws-cdk/aws-iam:minimizePolicies': true,
    '@aws-cdk/core:validateSnapshotRemovalPolicy': true,
    '@aws-cdk/aws-ecs:disableEcsImdsBlocking': true,
    '@aws-cdk/core:target-partitions': ['aws'],
  },
});

// Parity with the non-projen template's `deploy:platform` script. The platform stack
// is deployed by hand; projen's own `deploy` task would deploy every stack, including
// the service stack that belongs to the pipeline.
project.addTask('deploy:platform', {
  description: 'Deploy the long-lived platform stack (by hand, not from the pipeline)',
  exec: 'cdk deploy testing-ecs-truly-auto-mode-platform',
});

project.synth();
