// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: (whole manifest)
//
// The concrete, typed projection of the manifest. The stacks read this and nothing
// else — no AWS lookups, no cdk.context.json, no credentials required at synth time.
//
// Edit the manifest and re-run the skill rather than editing this file directly.

import { AppConfig, PipelineConfig } from './config';

export const config: AppConfig = {
  name: 'testing-ecs-truly-auto-mode',
  env: { account: '581514672367', region: 'us-east-1' },
  ssmPrefix: '/ecs-auto-mode/testing-ecs-truly-auto-mode',
  cdkQualifier: 'hnb659fds',

  architecture: 'ARM64',
  containerPort: 8080,
  healthCheck: {
    type: 'http',
    path: '/api/',
  },
  // No cost knob here carried a question in the plan, so this is the smallest valid
  // Fargate task — one that fits comfortably under any account's default service
  // quota. Adjust directly here if this workload needs more; it's a routine,
  // non-immutable change.
  sizing: { cpu: 256, memoryLimitMiB: 512, desiredCount: 1 },

  // No outbound call in app.py leaves the VPC (app.py:20 ssm, app.py:65/109 dsql) —
  // both have VPC interface endpoints. See analysis.egress in the manifest.
  egress: 'none',
  awsServices: ['ecr', 'ecr-docker', 'logs', 's3', 'ssm', 'dsql-data'],

  network: {
    mode: 'create',
    availabilityZones: ['us-east-1a', 'us-east-1b'],
  },
  cluster: { mode: 'create' },
  repository: { mode: 'create' },
  logGroup: { mode: 'create' },
  logRetentionDays: 30,

  loadBalancer: { mode: 'create' },

  publicHostname: {
    hostname: 'testing-ecs-truly-auto-mode.sandbox.defiance.ai',
    certificate: { mode: 'create' },
    hostedZoneId: 'Z096698834X7NH86OV1OR',
    zoneName: 'sandbox.defiance.ai',
  },

  networkDatastores: [],
  apiDatastores: [],
  iamAuthDatastores: [
    {
      id: 'dsql-cluster',
      kind: 'dsql',
      port: 5432,
      // app_user, not admin — see analysis.datastores[0].dbUser in the manifest.
      actions: ['dsql:DbConnect'],
      dbUser: 'app_user',
      mode: 'create',
      endpointParameter: 'dsql-cluster/endpoint',
    },
  ],

  // Plaintext — see analysis.config.environment in the manifest for why each is safe
  // to record as a literal rather than a secret.
  environment: {
    DSQL_CLUSTER_USER: 'app_user',
    DSQL_DATABASE: 'postgres',
    DSQL_PORT: '5432',
    DSQL_SSLROOTCERT: '/etc/ssl/certs/ca-certificates.crt',
  },
  // The cluster's endpoint is a deploy-time value — published by the platform stack
  // under the suffix named in iamAuthDatastores[0].endpointParameter above.
  environmentFromSsm: {
    DSQL_CLUSTER_ENDPOINT: 'dsql-cluster/endpoint',
  },
  secrets: [],
};

export const pipeline: PipelineConfig = {
  target: 'github-actions',
  branch: 'main',
  repository: 'mbonig/testing-ecs-auto-mode-2',
  // Found in the account — see plan.resources[].id === 'github-oidc-provider'.
  oidcProvider: {
    mode: 'adopt',
    providerArn: 'arn:aws:iam::581514672367:oidc-provider/token.actions.githubusercontent.com',
  },
};
