// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: (whole manifest)
//
// This file is the concrete, typed projection of the manifest. The stacks read it
// and nothing else, which is what keeps `cdk synth` hermetic — no AWS lookups, no
// cdk.context.json, no credentials required.
//
// Edit the manifest and re-run the skill rather than editing this file. The skill
// detects edits here and will ask before overwriting.

export type Architecture = 'ARM64' | 'X86_64';
export type EgressClassification = 'none' | 'public';

/**
 * AWS services the workload calls, used to decide which VPC endpoints exist.
 * `s3` is always present in isolated mode: ECR stores image layers in S3, so a task
 * cannot pull its image without the gateway endpoint.
 */
export type AwsServiceKey =
  | 'ecr' | 'ecr-docker' | 'logs' | 'secretsmanager' | 'ssm'
  | 's3' | 'dynamodb' | 'sqs' | 'sns' | 'kms' | 'sts' | 'events'
  | 'dsql-data' | 'dsql';

/**
 * Networking is either created or imported from explicit attributes. There is
 * deliberately no "look it up" variant — `Vpc.fromLookup` would require credentials
 * at synth time and write a cdk.context.json that goes stale.
 */
export type NetworkConfig =
  | {
      readonly mode: 'create';
      /**
       * Explicit AZ names, two minimum — an ALB requires two.
       *
       * These are recorded during planning rather than discovered at synth on
       * purpose. `maxAzs` makes the CDK resolve the account's AZ list through a
       * context lookup, which needs credentials and writes a cdk.context.json that
       * goes stale. Naming them here keeps synth offline and deterministic.
       */
      readonly availabilityZones: string[];
    }
  | {
      readonly mode: 'adopt';
      readonly vpcId: string;
      readonly availabilityZones: string[];
      readonly isolatedSubnetIds?: string[];
      readonly privateSubnetIds?: string[];
      readonly publicSubnetIds?: string[];
    };

/** A resource that is either created here or imported by identifier. */
export type Adoptable<T> = { readonly mode: 'create' } | ({ readonly mode: 'adopt' } & T);

/**
 * A public hostname served over HTTPS.
 *
 * The hosted zone is always adopted — creating one means delegating nameservers at a
 * registrar, which is outside what this tool can verify. That is also what makes a
 * *created* certificate possible: DNS validation needs a zone to write its validation
 * record into, so the zone, not the certificate, is what gates a public hostname.
 */
export interface PublicHostname {
  readonly hostname: string;
  /**
   * Created DNS-validated against the zone below, or imported by ARN. An imported
   * certificate must already be `ISSUED` and in the load balancer's region — a
   * `us-east-1` certificate cut for CloudFront is the usual mistake.
   */
  readonly certificate: Adoptable<{ certificateArn: string }>;
  readonly hostedZoneId: string;
  readonly zoneName: string;
}

/**
 * A network-reached datastore: needs a security group rule, not IAM.
 *
 * Created and adopted are genuinely different shapes rather than one shape with
 * optional fields. An adopted store is an endpoint and a security group that belong
 * to someone else; a created one is an instance this stack owns, whose endpoint does
 * not exist until it is deployed. Collapsing the two into optional fields is how a
 * `create` decision ends up producing nothing at all.
 *
 * Everything created here is retained on stack deletion, and databases also carry
 * deletion protection. The asymmetry is the whole reason: a retained instance costs
 * money and can be deleted by hand in a minute, while a destroyed one is gone.
 */
export type NetworkDatastore = { readonly id: string } & (
  | {
      readonly mode: 'adopt';
      readonly kind: 'rds' | 'elasticache' | 'documentdb';
      readonly securityGroupId: string;
      readonly port: number;
      readonly endpointAddress: string;
    }
  | ({ readonly mode: 'create' } & CreatedNetworkDatastore)
);

/**
 * A network-reached datastore this stack builds.
 *
 * The parameters here are the ones that carry a standing monthly cost or a durability
 * consequence, which is why they are recorded from an explicit question rather than
 * defaulted — see references/planning/resource-catalog.md.
 */
export type CreatedNetworkDatastore = {
  /**
   * SSM parameter suffixes the platform stack publishes this datastore's endpoint and
   * port under.
   *
   * The suffixes are carried in the config rather than derived independently on both
   * sides, because the publisher and the reader agreeing on a name is the entire
   * contract: derive it twice and a rename in one place produces a container reading a
   * parameter nobody wrote, which fails at task start with nothing pointing at the cause.
   */
  readonly endpointParameter: string;
  readonly portParameter: string;
} & (
  | {
      readonly kind: 'rds';
      /** Postgres, MySQL, MariaDB, SQL Server or Oracle. Aurora is adopt-only: a cluster's writer/reader topology is not derivable from application code. */
      readonly engine: 'postgres' | 'mysql' | 'mariadb' | 'sqlserver' | 'oracle';
      readonly engineVersion: string;
      readonly instanceClass: string;
      readonly allocatedStorageGb: number;
      readonly multiAz: boolean;
      readonly port: number;
      /**
       * Where the container reads this database's credentials from.
       *
       * A created database's credentials are generated, so they cannot be named in the
       * plan — the stack makes the secret and the service stack injects its fields.
       */
      readonly credentials: DatabaseCredentials;
    }
  | {
      readonly kind: 'elasticache';
      readonly engine: 'redis' | 'memcached';
      readonly nodeType: string;
      /** Redis only. Memcached scales by node count instead. */
      readonly replicaCount?: number;
      readonly port: number;
    }
  | {
      readonly kind: 'documentdb';
      readonly instanceClass: string;
      readonly instanceCount: number;
      readonly port: number;
      readonly credentials: DatabaseCredentials;
    }
);

/**
 * How a created database's generated credentials reach the container.
 *
 * `fields` maps each environment variable the application reads onto a field of the
 * generated secret, injected through the execution role.
 *
 * There is deliberately no `url` variant. A generated secret holds host, port,
 * username, password and dbname; it does not hold an assembled connection URL, and
 * composing one would mean something reading the password to build it. An application
 * that reads a single `DATABASE_URL` is served by an *adopted* secret — recorded in
 * `AppConfig.secrets` like any other — while the database itself is still created.
 * Planning refuses to complete a plan that needs a URL this cannot supply, rather than
 * generating five variables the application never looks at.
 */
export interface DatabaseCredentials {
  /**
   * SSM parameter suffix carrying the created secret's ARN. The ARN is a deploy-time
   * value, so it travels through the platform → service contract like every other one.
   */
  readonly secretArnParameter: string;
  /** Environment variable name → field of the secret that supplies it. */
  readonly fields: Record<string, 'host' | 'port' | 'username' | 'password' | 'dbname'>;
}

/**
 * An API-reached datastore: needs task-role permissions, not a security group rule.
 *
 * The `actions` are shared by both modes — what the application does with the resource
 * does not depend on who made it. What differs is where the ARN comes from: an adopted
 * store names it outright, and a created one has no ARN until the stack is deployed,
 * so the grant is written against the construct instead.
 */
export type ApiDatastore = { readonly id: string; readonly actions: string[] } & (
  | {
      readonly mode: 'adopt';
      readonly kind: 'dynamodb' | 's3' | 'sqs' | 'sns';
      /** Exact resource ARNs. Never a wildcard — uncertainty belongs in the plan, not the policy. */
      readonly resourceArns: string[];
    }
  | ({ readonly mode: 'create' } & CreatedApiDatastore)
);

/** An API-reached datastore this stack builds. All are retained on stack deletion. */
export type CreatedApiDatastore = {
  /**
   * SSM parameter suffix the platform stack publishes this resource's name under —
   * its table name, bucket name, queue URL or topic ARN. Same reasoning as
   * `CreatedNetworkDatastore.endpointParameter`: one recorded name, two users.
   */
  readonly attributeParameter: string;
} & (
  | {
      readonly kind: 'dynamodb';
      /**
       * A table's key schema is immutable — a wrong partition key is fixed by deleting
       * and rebuilding a table that may by then hold data, not by altering it. That is
       * why planning refuses `create` on a table whose key schema is below high
       * confidence and unconfirmed, and why there is no default for it here.
       */
      readonly partitionKey: TableAttribute;
      readonly sortKey?: TableAttribute;
      /** Only the indexes the code was found to query — an unqueried index is a standing write cost. */
      readonly indexes?: TableIndex[];
    }
  | { readonly kind: 's3' }
  | { readonly kind: 'sqs' }
  | { readonly kind: 'sns' }
);

/**
 * An IAM-authenticated network datastore: reached over TCP like a database, but
 * authorised by IAM like an API. Neither `NetworkDatastore` nor `ApiDatastore` can
 * express Aurora DSQL without lying — it has a port and an endpoint like the former,
 * but no security group and no password like the latter. It is a third category, not
 * a variation on the other two.
 *
 * There is deliberately no `SecretRef` and no `DatabaseCredentials` for this kind: the
 * driver authenticates with a short-lived SigV4 token signed by the task role, so no
 * password exists anywhere in the system. Recording one would be a bug, not an omission.
 */
export type IamAuthDatastore = {
  readonly id: string;
  readonly kind: 'dsql';
  /** PostgreSQL wire protocol for DSQL. */
  readonly port: number;
  /** `dsql:DbConnect` for a named database role, `dsql:DbConnectAdmin` for `admin`. */
  readonly actions: string[];
  /** The database role the application logs in as. `admin` is the superuser. */
  readonly dbUser: string;
} & (
  | {
      readonly mode: 'adopt';
      readonly clusterIdentifier: string;
      /**
       * The data-plane VPC endpoint service to connect through when `egress` is
       * `none`. Absent when `egress` is `public` — there is nothing to build. The
       * service name is region-specific and opaque, so it is resolved once during
       * planning and recorded here rather than derived.
       */
      readonly vpcEndpointServiceName?: string;
    }
  | {
      readonly mode: 'create';
      /**
       * SSM parameter suffix the platform stack publishes the cluster's endpoint
       * under. Recorded here rather than derived independently in two places — same
       * reasoning as `CreatedNetworkDatastore.endpointParameter`.
       */
      readonly endpointParameter: string;
    }
);

export interface TableAttribute {
  readonly name: string;
  readonly type: 'string' | 'number' | 'binary';
}

export interface TableIndex {
  readonly name: string;
  readonly partitionKey: TableAttribute;
  readonly sortKey?: TableAttribute;
}

export interface SecretRef {
  /** Environment variable name the container reads. */
  readonly name: string;
  readonly source: 'secretsmanager' | 'ssm';
  /** ARN of the secret, or the SSM parameter name. A pointer — never a value. */
  readonly arn: string;
  /** Key within a JSON-valued Secrets Manager secret. */
  readonly jsonKey?: string;
  /** Customer-managed KMS key, if the secret uses one. The execution role needs kms:Decrypt. */
  readonly kmsKeyArn?: string;
}

export interface HealthCheckConfig {
  readonly type: 'http' | 'tcp';
  /** Present only when type is 'http'. */
  readonly path?: string;
  readonly healthyThresholdCount?: number;
  readonly interval?: number;
}

export interface ServiceSizing {
  readonly cpu: number;
  readonly memoryLimitMiB: number;
  readonly desiredCount: number;
}

export interface AppConfig {
  readonly name: string;
  readonly env: { readonly account: string; readonly region: string };
  /** SSM path prefix carrying the platform → service contract. */
  readonly ssmPrefix: string;
  /**
   * The target account's CDK bootstrap qualifier — `hnb659fds` unless the account
   * was bootstrapped with `cdk bootstrap --qualifier <value>`. Names the bootstrap
   * roles the deploy role is granted `sts:AssumeRole` on; see deploy-permissions.ts.
   */
  readonly cdkQualifier: string;

  readonly architecture: Architecture;
  readonly containerPort: number;
  readonly healthCheck: HealthCheckConfig;
  readonly sizing: ServiceSizing;

  /**
   * Decides subnet placement and whether a NAT gateway exists. Derived from the
   * egress analysis, never defaulted — see references/analysis/egress.md.
   */
  readonly egress: EgressClassification;
  readonly awsServices: AwsServiceKey[];

  readonly network: NetworkConfig;
  readonly cluster: Adoptable<{ clusterName: string }>;
  readonly repository: Adoptable<{ repositoryName: string }>;
  readonly logGroup: Adoptable<{ logGroupName: string }>;
  readonly logRetentionDays: number;

  /** Absent when the service takes no inbound traffic. */
  readonly loadBalancer?: Adoptable<{
    loadBalancerArn: string;
    securityGroupId: string;
    listenerArn: string;
    /** Required when adopting a shared listener, or it hijacks other traffic. */
    listenerRuleHostHeader?: string;
  }>;

  readonly publicHostname?: PublicHostname;

  readonly networkDatastores: NetworkDatastore[];
  readonly apiDatastores: ApiDatastore[];
  readonly iamAuthDatastores: IamAuthDatastore[];

  readonly environment: Record<string, string>;
  /**
   * Environment variables whose values are published SSM parameters rather than
   * literals: variable name → parameter suffix under `ssmPrefix`.
   *
   * This exists because a created resource's physical id is a *deploy-time* value.
   * A created table's name is not known when the service stack is synthesized, so
   * `environment` — a `Record<string, string>` of literals — cannot carry it, and
   * without somewhere to put it the table gets created and the container has no way
   * to address it. The service stack resolves these the same way it already resolves
   * the cluster name and the subnet ids.
   *
   * Created resources use this; adopted ones keep using `environment`, because their
   * names were known at planning time. A name appearing in both is an error, not a
   * precedence question.
   */
  readonly environmentFromSsm: Record<string, string>;
  readonly secrets: SecretRef[];
}

/**
 * The pipeline's own shape — kept separate from `AppConfig`, which is a pure
 * projection of the resource plan. `bin/app.ts` reads this to decide whether the
 * platform stack needs the GitHub OIDC role.
 */
export type PipelineConfig =
  | {
      readonly target: 'github-actions';
      readonly branch: string;
      readonly repository: string;
      /**
       * Whether this account already has an OIDC provider for
       * `token.actions.githubusercontent.com`. Most do, and creating a second fails
       * with `EntityAlreadyExists` — but an account that genuinely has none needs one,
       * so this is a decision rather than a constant.
       *
       * Deliberately a union rather than an optional ARN. An absent optional field
       * means "create" by omission, which is exactly how a stack that fails on every
       * account with an existing provider shipped in the first place.
       */
      readonly oidcProvider: Adoptable<{ providerArn: string }>;
    }
  | { readonly target: 'codepipeline'; readonly branch: string };
