// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: plan.resources, analysis.egress
//
// The platform stack. Everything here changes rarely — networking, the cluster, the
// registry, load balancing, roles, logging, DNS. Routine deploys touch the *service*
// stack instead, which is why the two are separate.
//
// This stack publishes everything the service stack needs to SSM Parameter Store.
// It deliberately does not use CloudFormation exports: Fn::ImportValue would lock
// this stack against changes while the service stack imported from it, which is
// exactly the wrong coupling between a rarely-changing stack and a constantly-
// changing one.
//
// HAND-MODIFIED beyond the skill's standard template: buildIamAuthDatastores() and
// the constructor below wire in DsqlRoleGrant (./dsql-bootstrap.ts), a user-requested
// addition that runs the CREATE ROLE / AWS IAM GRANT step the skill otherwise
// documents as a manual, post-deploy action. See .ecs-auto-mode/manifest.yaml,
// plan.resources[].id === 'dsql-role-grant'.

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as targets from 'aws-cdk-lib/aws-route53-targets';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as docdb from 'aws-cdk-lib/aws-docdb';
import * as elasticache from 'aws-cdk-lib/aws-elasticache';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as dsql from 'aws-cdk-lib/aws-dsql';
import { AppConfig, AwsServiceKey, CreatedApiDatastore, IamAuthDatastore, TableAttribute } from './config';
import { GitHubOidcRole } from './deploy-permissions';
import { DsqlRoleGrant } from './dsql-bootstrap';

export interface PlatformStackGitHubActions {
  readonly repository: string;
  readonly branch: string;
  /**
   * Set when the plan recorded that this account already has an OIDC provider for
   * `token.actions.githubusercontent.com` — creating a second fails with
   * `EntityAlreadyExists`. Absent means the plan recorded that the account has none,
   * and one is created here.
   *
   * The entry point maps this from `pipeline.oidcProvider`, which is a decision, not
   * an optional value: nothing reaches this prop without planning having looked in the
   * account or asked.
   */
  readonly existingProviderArn?: string;
}

export interface PlatformStackProps extends cdk.StackProps {
  readonly config: AppConfig;
  /**
   * Present only when the recorded pipeline target is `github-actions`. Wires the
   * GitHub OIDC-trusted deploy role into this stack, using the task role, execution
   * role, cluster and repository already constructed here — see deploy-permissions.ts.
   * Absent for `codepipeline`, which authenticates through a CodeStar connection
   * instead.
   */
  readonly githubActions?: PlatformStackGitHubActions;
}

/**
 * What the rest of the stack needs to know about one IAM-authenticated datastore,
 * once it has been either created here or resolved from the plan.
 *
 * Resolving this once is what keeps the endpoint/egress coupling from being repeated:
 * the hostname the task connects to is not the same string in isolated and public
 * modes, and the certificate the server presents is cut for whichever one is correct.
 * Choosing the wrong one does not fail closed — the connection hangs until the
 * driver's connect timeout.
 */
interface IamAuthDatastoreRefs {
  readonly store: IamAuthDatastore;
  /** `arn:aws:dsql:<region>:<account>:cluster/<id>` — what the task role is scoped to. */
  readonly clusterArn: string;
  /**
   * The endpoint service to put an interface endpoint on, for isolated placement.
   * Absent when `egress` is `public` — there is nothing to build.
   */
  readonly endpointServiceName?: string;
  /**
   * The cluster's *public* hostname, always — independent of `egress`. Used only by
   * `DsqlRoleGrant` (./dsql-bootstrap.ts), whose bootstrap Lambda runs outside the
   * VPC and so never needs the data-plane VPC endpoint the task itself may use.
   */
  readonly publicEndpoint: string;
}

export class PlatformStack extends cdk.Stack {
  public readonly vpc: ec2.IVpc;
  public readonly cluster: ecs.ICluster;
  public readonly repository: ecr.IRepository;

  private readonly config: AppConfig;
  private readonly githubActions?: PlatformStackGitHubActions;

  /**
   * Parameter suffix → value, for every created datastore attribute the service stack
   * or an operator needs. Filled while the datastores are built and written out by
   * `publishParameters`, because a created resource's endpoint, table name or secret
   * ARN is a deploy-time value that cannot be known when the service stack synthesizes.
   *
   * The suffixes come from the config rather than being derived here — see
   * `CreatedNetworkDatastore.endpointParameter`.
   */
  private readonly datastoreParameters = new Map<string, string>();

  /**
   * Serving AZs from config rather than the default implementation is what keeps
   * synth offline. The base implementation performs a context lookup against the
   * target account, which fails outright without credentials — and a pipeline that
   * synthesizes this stack should not need them.
   */
  public get availabilityZones(): string[] {
    return this.config.network.mode === 'create'
      ? this.config.network.availabilityZones
      : this.config.network.availabilityZones;
  }

  constructor(scope: Construct, id: string, props: PlatformStackProps) {
    super(scope, id, props);
    const config = (this.config = props.config);
    this.githubActions = props.githubActions;

    this.vpc = this.buildVpc();

    // Before the endpoints, deliberately: an isolated task reaches DSQL through a
    // data-plane interface endpoint whose service name this resolves, either off the
    // created cluster's own attribute or off the plan's recorded value.
    const iamAuthDatastores = this.buildIamAuthDatastores();

    // Isolated placement means no NAT, so every AWS call the task makes has to go
    // through a VPC endpoint. See references/analysis/egress.md for why this is the
    // decision worth getting right.
    if (config.egress === 'none') {
      this.addVpcEndpoints(this.vpc, iamAuthDatastores);
    }

    this.cluster = this.buildCluster(this.vpc);
    this.repository = this.buildRepository();

    const logGroup = this.buildLogGroup();
    const taskSecurityGroup = this.buildTaskSecurityGroup(this.vpc);

    // The execution role is built before the datastores because a *created* database
    // owns its own generated secret, and the stack that owns both is the one that
    // grants read on it — no ARN travels through the config and no wildcard is needed.
    const executionRole = this.buildExecutionRole();

    this.wireNetworkDatastores(taskSecurityGroup, executionRole);

    // Created API-reached resources have no ARN until they exist, so they are built
    // first and the task role is granted against what came back. IAM-authenticated
    // datastores join the same grant list: the connection itself is authorised here,
    // by the task role, rather than by a password.
    const taskRole = this.buildTaskRole([
      ...this.buildApiDatastores(),
      ...iamAuthDatastores.map((ref) => ({
        id: ref.store.id,
        actions: ref.store.actions,
        resourceArns: [ref.clusterArn],
      })),
    ]);

    const targetGroup = config.loadBalancer
      ? this.buildLoadBalancing(this.vpc, taskSecurityGroup)
      : undefined;

    this.buildGitHubOidcRole({ taskRole, executionRole });

    this.buildDsqlRoleGrants(iamAuthDatastores, taskRole);

    this.publishParameters({ logGroup, taskSecurityGroup, executionRole, taskRole, targetGroup });
  }

  /**
   * Links each non-admin DSQL database role to the task role via `AWS IAM GRANT`, so
   * the manual post-deploy SQL step this tool otherwise documents as required isn't
   * necessary. Skipped for `admin`: DSQL's built-in admin role needs no such link —
   * `dsql:DbConnectAdmin` alone authorises it.
   *
   * User-requested addition beyond the standard resource catalog — see
   * .ecs-auto-mode/manifest.yaml, plan.resources[].id === 'dsql-role-grant'.
   */
  private buildDsqlRoleGrants(iamAuthDatastores: IamAuthDatastoreRefs[], taskRole: iam.IRole): void {
    for (const ref of iamAuthDatastores) {
      if (ref.store.dbUser === 'admin') continue;
      new DsqlRoleGrant(this, `DsqlRoleGrant${pascal(ref.store.id)}`, {
        clusterResourceArn: ref.clusterArn,
        publicEndpoint: ref.publicEndpoint,
        region: this.region,
        dbUser: ref.store.dbUser,
        taskRoleArn: taskRole.roleArn,
      });
    }
  }

  // ---------------------------------------------------------------- networking

  /**
   * Subnet layout follows the egress classification. An isolated workload gets no
   * NAT gateway at all, which is the single largest standing cost this tool avoids.
   */
  private buildVpc(): ec2.IVpc {
    const { network, egress } = this.config;

    if (network.mode === 'adopt') {
      // Route tables belong to whoever owns the adopted VPC; this stack only places
      // resources into the subnets and never inspects their routing.
      cdk.Annotations.of(this).acknowledgeWarning(
        '@aws-cdk/aws-ec2:noSubnetRouteTableId',
        'Adopted subnets are used for placement only; their routing is not managed here',
      );
      // Explicit attributes, never fromLookup — synth must work without credentials.
      return ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
        vpcId: network.vpcId,
        availabilityZones: network.availabilityZones,
        isolatedSubnetIds: network.isolatedSubnetIds,
        privateSubnetIds: network.privateSubnetIds,
        publicSubnetIds: network.publicSubnetIds,
      });
    }

    const appSubnet: ec2.SubnetConfiguration =
      egress === 'none'
        ? { name: 'app', subnetType: ec2.SubnetType.PRIVATE_ISOLATED, cidrMask: 22 }
        : { name: 'app', subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 22 };

    return new ec2.Vpc(this, 'Vpc', {
      availabilityZones: network.availabilityZones,
      // Zero NAT gateways when nothing needs to reach the internet.
      natGateways: egress === 'none' ? 0 : network.availabilityZones.length,
      subnetConfiguration: [
        { name: 'public', subnetType: ec2.SubnetType.PUBLIC, cidrMask: 24 },
        appSubnet,
      ],
    });
  }

  /** The subnets tasks and endpoints live in, derived from the egress classification. */
  private get appSubnets(): ec2.SubnetSelection {
    return {
      subnetType:
        this.config.egress === 'none'
          ? ec2.SubnetType.PRIVATE_ISOLATED
          : ec2.SubnetType.PRIVATE_WITH_EGRESS,
    };
  }

  /**
   * Interface endpoints for exactly the services the analysis found, plus the two
   * gateway endpoints. Endpoints are not free — an interface endpoint bills hourly
   * per AZ — so this provisions what is used rather than everything available.
   */
  private addVpcEndpoints(vpc: ec2.IVpc, iamAuthDatastores: IamAuthDatastoreRefs[]): void {
    const endpointSg = new ec2.SecurityGroup(this, 'EndpointSecurityGroup', {
      vpc,
      description: 'Allows tasks to reach VPC interface endpoints over 443',
      allowAllOutbound: false,
    });
    endpointSg.addIngressRule(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(443),
      'HTTPS from within the VPC',
    );

    const interfaceServices: Partial<Record<AwsServiceKey, ec2.InterfaceVpcEndpointAwsService>> = {
      ecr: ec2.InterfaceVpcEndpointAwsService.ECR,
      'ecr-docker': ec2.InterfaceVpcEndpointAwsService.ECR_DOCKER,
      logs: ec2.InterfaceVpcEndpointAwsService.CLOUDWATCH_LOGS,
      secretsmanager: ec2.InterfaceVpcEndpointAwsService.SECRETS_MANAGER,
      ssm: ec2.InterfaceVpcEndpointAwsService.SSM,
      sqs: ec2.InterfaceVpcEndpointAwsService.SQS,
      sns: ec2.InterfaceVpcEndpointAwsService.SNS,
      kms: ec2.InterfaceVpcEndpointAwsService.KMS,
      sts: ec2.InterfaceVpcEndpointAwsService.STS,
      events: ec2.InterfaceVpcEndpointAwsService.EVENTBRIDGE,
      // The DSQL *control* plane — CreateCluster, ListClusters. Present only when the
      // application actually manages clusters. Generating a connection auth token does
      // not call it: `generate_db_connect_auth_token` and its admin twin are local
      // SigV4 presigners that make no request at all. An app that only connects and is
      // handed this endpoint pays roughly $7/mo per AZ for nothing.
      dsql: ec2.InterfaceVpcEndpointAwsService.DSQL_MANAGEMENT,
    };

    for (const key of this.config.awsServices) {
      const service = interfaceServices[key];
      if (!service) continue; // s3 and dynamodb are gateway endpoints, handled below
      new ec2.InterfaceVpcEndpoint(this, `Endpoint${pascal(key)}`, {
        vpc,
        service,
        subnets: this.appSubnets,
        securityGroups: [endpointSg],
        // Without private DNS the SDK still resolves the public endpoint and hangs.
        privateDnsEnabled: true,
      });
    }

    // Always present: ECR stores image layers in S3, so a task in isolated subnets
    // cannot pull its image without this — and the resulting error never mentions S3.
    new ec2.GatewayVpcEndpoint(this, 'EndpointS3', {
      vpc,
      service: ec2.GatewayVpcEndpointAwsService.S3,
      subnets: [this.appSubnets],
    });

    if (this.config.awsServices.includes('dynamodb')) {
      new ec2.GatewayVpcEndpoint(this, 'EndpointDynamoDb', {
        vpc,
        service: ec2.GatewayVpcEndpointAwsService.DYNAMODB,
        subnets: [this.appSubnets],
      });
    }

    this.addDsqlDataPlaneEndpoints(vpc, endpointSg, iamAuthDatastores);
  }

  /**
   * Interface endpoints for the DSQL *data plane*, one per cluster in the plan.
   *
   * Aurora DSQL is reached over the PostgreSQL wire protocol, so unlike every other
   * endpoint here this one is not HTTPS on 443 — the ENI has to accept 5432, and the
   * shared endpoint security group is opened for it only when such an endpoint exists.
   *
   * The endpoint service name is region-specific and opaque
   * (`com.amazonaws.us-east-1.dsql-fnh4`), so it comes from the cluster's own
   * `VpcEndpointServiceName` attribute on the create path and from a planning-time
   * lookup on the adopt path — never hardcoded, which would synthesize a stack that
   * deploys in one region and fails in every other.
   *
   * `privateDnsEnabled` matters more here than usual: `InterfaceVpcEndpointService`
   * defaults it off, and without it the driver resolves the public hostname and hangs
   * rather than failing.
   */
  private addDsqlDataPlaneEndpoints(
    vpc: ec2.IVpc,
    endpointSg: ec2.SecurityGroup,
    iamAuthDatastores: IamAuthDatastoreRefs[],
  ): void {
    const withEndpointService = iamAuthDatastores.filter((ref) => ref.endpointServiceName);
    if (withEndpointService.length === 0) return;

    endpointSg.addIngressRule(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(5432),
      'PostgreSQL wire protocol to the DSQL data plane from within the VPC',
    );

    for (const ref of withEndpointService) {
      new ec2.InterfaceVpcEndpoint(this, `EndpointDsql${pascal(ref.store.id)}`, {
        vpc,
        service: new ec2.InterfaceVpcEndpointService(ref.endpointServiceName!, ref.store.port),
        subnets: this.appSubnets,
        securityGroups: [endpointSg],
        privateDnsEnabled: true,
      });
    }
  }

  // ------------------------------------------------------------------- compute

  private buildCluster(vpc: ec2.IVpc): ecs.ICluster {
    const { cluster } = this.config;
    if (cluster.mode === 'adopt') {
      return ecs.Cluster.fromClusterAttributes(this, 'Cluster', {
        clusterName: cluster.clusterName,
        vpc,
        securityGroups: [],
      });
    }
    // Container Insights is deliberately not enabled here. It is genuinely useful,
    // but it bills per metric and this tool does not turn on standing costs the user
    // did not ask for. Enable it explicitly if you want it.
    return new ecs.Cluster(this, 'Cluster', {
      vpc,
      clusterName: `${this.config.name}-cluster`,
    });
  }

  private buildRepository(): ecr.IRepository {
    const { repository } = this.config;
    if (repository.mode === 'adopt') {
      return ecr.Repository.fromRepositoryName(this, 'Repository', repository.repositoryName);
    }
    return new ecr.Repository(this, 'Repository', {
      repositoryName: this.config.name,
      imageScanOnPush: true,
      // Unbounded image retention is a slow, invisible storage cost.
      lifecycleRules: [{ maxImageCount: 20, description: 'Retain the last 20 images' }],
    });
  }

  private buildLogGroup(): logs.ILogGroup {
    const { logGroup } = this.config;
    if (logGroup.mode === 'adopt') {
      return logs.LogGroup.fromLogGroupName(this, 'LogGroup', logGroup.logGroupName);
    }
    return new logs.LogGroup(this, 'LogGroup', {
      logGroupName: `/ecs/${this.config.name}`,
      // The CDK default is infinite retention, which is a real and permanent cost.
      retention: retentionDays(this.config.logRetentionDays),
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });
  }

  // ------------------------------------------------------------------ security

  private buildTaskSecurityGroup(vpc: ec2.IVpc): ec2.SecurityGroup {
    return new ec2.SecurityGroup(this, 'TaskSecurityGroup', {
      vpc,
      description: `Tasks for ${this.config.name}`,
      allowAllOutbound: true,
    });
  }

  /**
   * Network-reached datastores need an ingress rule allowing the task group in on the
   * engine port. This is the piece most often missed, and it fails as a connection
   * timeout at startup rather than a clear permission error.
   *
   * The two modes differ in whose security group that rule lands on. An adopted
   * datastore's group belongs to someone else and is imported to have one rule added;
   * a created datastore's group is defined here, so there is nothing to import and
   * nothing of anyone else's to mutate.
   */
  private wireNetworkDatastores(taskSg: ec2.ISecurityGroup, executionRole: iam.IRole): void {
    for (const store of this.config.networkDatastores) {
      if (store.mode === 'adopt') {
        const storeSg = ec2.SecurityGroup.fromSecurityGroupId(
          this,
          `DatastoreSg${pascal(store.id)}`,
          store.securityGroupId,
          // The datastore's security group is not ours to own or mutate wholesale.
          { mutable: true },
        );
        storeSg.addIngressRule(
          taskSg,
          ec2.Port.tcp(store.port),
          // Restricted charset — see the note on the load balancer rule below.
          `${this.config.name} tasks to ${store.id}`,
        );
        continue;
      }

      const storeSg = new ec2.SecurityGroup(this, `DatastoreSg${pascal(store.id)}`, {
        vpc: this.vpc,
        description: `${store.kind} ${store.id} for ${this.config.name}`,
        allowAllOutbound: false,
      });
      storeSg.addIngressRule(
        taskSg,
        ec2.Port.tcp(store.port),
        `${this.config.name} tasks to ${store.id}`,
      );

      switch (store.kind) {
        case 'rds':
          this.buildDatabaseInstance(store, storeSg, executionRole);
          break;
        case 'documentdb':
          this.buildDocumentDbCluster(store, storeSg, executionRole);
          break;
        case 'elasticache':
          this.buildElastiCache(store, storeSg);
          break;
      }
    }
  }

  /** Records a created datastore attribute for `publishParameters` to write out. */
  private recordParameter(suffix: string, value: string): void {
    if (this.datastoreParameters.has(suffix)) {
      throw new Error(
        `two datastores publish the SSM parameter suffix "${suffix}" — one would overwrite the other, and the container would read whichever deployed last`,
      );
    }
    this.datastoreParameters.set(suffix, value);
  }

  /**
   * A created relational database.
   *
   * Retained and deletion-protected on purpose: a retained instance costs money and
   * can be deleted by hand in a minute, while a destroyed one is gone. That asymmetry
   * is total, so the default sits on the safe side of it and the plan says so.
   *
   * The first deploy of this stack blocks for tens of minutes while the instance is
   * provisioned. That is stated in the plan too — it is not a hang.
   */
  private buildDatabaseInstance(
    store: Extract<AppConfig['networkDatastores'][number], { mode: 'create'; kind: 'rds' }>,
    securityGroup: ec2.ISecurityGroup,
    executionRole: iam.IRole,
  ): void {
    const id = pascal(store.id);

    // The username carries no cost and no durability consequence, so it is fixed
    // rather than asked. It does not need to be memorable: the application reads it
    // out of the generated secret's `username` field.
    const secret = new secretsmanager.Secret(this, `DatastoreSecret${id}`, {
      // Deterministic, so the secret is findable by name in the console without
      // going via the stack's resource list.
      secretName: `${this.config.name}/${store.id}`,
      description: `Generated credentials for ${store.id}`,
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: 'appuser' }),
        generateStringKey: 'password',
        // The RDS-forbidden characters, plus the ones that break URL parsing for
        // applications that assemble a connection string from these fields.
        excludeCharacters: ' %+~`#$&*()|[]{}:;<>?!\'/@"\\,=',
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const instance = new rds.DatabaseInstance(this, `Datastore${id}`, {
      engine: databaseEngine(store.engine, store.engineVersion),
      // RDS instance classes are written `db.t4g.micro`; the CDK adds the `db.` prefix
      // itself, so passing it through would produce `db.db.t4g.micro`.
      instanceType: new ec2.InstanceType(store.instanceClass.replace(/^db\./, '')),
      vpc: this.vpc,
      vpcSubnets: this.appSubnets,
      securityGroups: [securityGroup],
      credentials: rds.Credentials.fromSecret(secret),
      allocatedStorage: store.allocatedStorageGb,
      multiAz: store.multiAz,
      port: store.port,
      // SQL Server and Oracle reject `databaseName` on an instance — a database is
      // created inside them afterwards instead. Postgres and MySQL take one, and the
      // application needs it, so it is set where it is accepted.
      databaseName: acceptsDatabaseName(store.engine) ? databaseName(this.config.name) : undefined,
      storageEncrypted: true,
      deletionProtection: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // This stack owns the secret and the execution role, so the grant is written here
    // rather than derived from an ARN in the config. Scoped to this one secret.
    secret.grantRead(executionRole);

    this.recordParameter(store.endpointParameter, instance.dbInstanceEndpointAddress);
    this.recordParameter(store.portParameter, instance.dbInstanceEndpointPort);
    this.recordParameter(store.credentials.secretArnParameter, secret.secretArn);
  }

  /** A created DocumentDB cluster. Retained and deletion-protected, as RDS is. */
  private buildDocumentDbCluster(
    store: Extract<AppConfig['networkDatastores'][number], { mode: 'create'; kind: 'documentdb' }>,
    securityGroup: ec2.ISecurityGroup,
    executionRole: iam.IRole,
  ): void {
    const id = pascal(store.id);

    const cluster = new docdb.DatabaseCluster(this, `Datastore${id}`, {
      masterUser: {
        username: 'appuser',
        secretName: `${this.config.name}/${store.id}`,
        excludeCharacters: ' %+~`#$&*()|[]{}:;<>?!\'/@"\\,=',
      },
      instanceType: new ec2.InstanceType(store.instanceClass.replace(/^db\./, '')),
      instances: store.instanceCount,
      vpc: this.vpc,
      vpcSubnets: this.appSubnets,
      securityGroup,
      port: store.port,
      storageEncrypted: true,
      deletionProtection: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // `secret` is optional on the type because a cluster can be given a password
    // directly. This one always generates, so an absent secret is a bug, not a case.
    if (!cluster.secret) {
      throw new Error(`DocumentDB cluster ${store.id} generated no secret to grant`);
    }
    cluster.secret.grantRead(executionRole);

    this.recordParameter(store.endpointParameter, cluster.clusterEndpoint.hostname);
    this.recordParameter(store.portParameter, cdk.Token.asString(cluster.clusterEndpoint.port));
    this.recordParameter(store.credentials.secretArnParameter, cluster.secret.secretArn);
  }

  /**
   * A created ElastiCache cluster.
   *
   * This is the one datastore built from L1 constructs: aws-cdk-lib ships no L2 for
   * ElastiCache. So there are no `grant*` methods here, the property names follow
   * CloudFormation rather than the CDK, and the retention policy is applied to the
   * resource directly instead of passed as a prop.
   *
   * At-rest encryption is on — it is transparent to the client. In-transit encryption
   * is deliberately *not*: it requires the application to connect over TLS, so turning
   * it on silently would break a client that connects in plaintext.
   */
  private buildElastiCache(
    store: Extract<AppConfig['networkDatastores'][number], { mode: 'create'; kind: 'elasticache' }>,
    securityGroup: ec2.ISecurityGroup,
  ): void {
    const id = pascal(store.id);

    const subnetGroup = new elasticache.CfnSubnetGroup(this, `DatastoreSubnets${id}`, {
      description: `${store.id} for ${this.config.name}`,
      subnetIds: this.vpc.selectSubnets(this.appSubnets).subnetIds,
    });

    if (store.engine === 'redis') {
      const group = new elasticache.CfnReplicationGroup(this, `Datastore${id}`, {
        replicationGroupDescription: `${store.id} for ${this.config.name}`,
        engine: 'redis',
        cacheNodeType: store.nodeType,
        // One primary plus the replicas asked for.
        numCacheClusters: 1 + (store.replicaCount ?? 0),
        automaticFailoverEnabled: (store.replicaCount ?? 0) > 0,
        cacheSubnetGroupName: subnetGroup.ref,
        securityGroupIds: [securityGroup.securityGroupId],
        atRestEncryptionEnabled: true,
        port: store.port,
      });
      group.addDependency(subnetGroup);
      group.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

      this.recordParameter(store.endpointParameter, group.attrPrimaryEndPointAddress);
      this.recordParameter(store.portParameter, group.attrPrimaryEndPointPort);
      return;
    }

    const cluster = new elasticache.CfnCacheCluster(this, `Datastore${id}`, {
      engine: 'memcached',
      cacheNodeType: store.nodeType,
      // Memcached scales by node count rather than by replicas.
      numCacheNodes: Math.max(1, store.replicaCount ?? 1),
      cacheSubnetGroupName: subnetGroup.ref,
      vpcSecurityGroupIds: [securityGroup.securityGroupId],
      port: store.port,
    });
    cluster.addDependency(subnetGroup);
    cluster.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

    this.recordParameter(store.endpointParameter, cluster.attrConfigurationEndpointAddress);
    this.recordParameter(store.portParameter, cluster.attrConfigurationEndpointPort);
  }

  /**
   * Create or resolve every IAM-authenticated datastore in the plan.
   *
   * A created cluster is the one place this tool creates a stateful resource outside
   * the datastore-create paths above, and the same two guards apply: deletion
   * protection on the cluster itself, and `RemovalPolicy.RETAIN` on the stack's claim
   * to it. DSQL is serverless with no capacity or version to choose and provisions in
   * about 30 seconds, which is what makes offering `create` here defensible.
   *
   * Unlike `wireNetworkDatastores`, this runs before the VPC endpoints are decided —
   * an isolated task reaches DSQL through a data-plane interface endpoint, and this is
   * where that endpoint's service name is resolved.
   */
  private buildIamAuthDatastores(): IamAuthDatastoreRefs[] {
    return this.config.iamAuthDatastores.map((store) => {
      if (store.mode === 'create') {
        const cluster = new dsql.CfnCluster(this, `DsqlCluster${pascal(store.id)}`, {
          deletionProtectionEnabled: true,
          tags: [{ key: 'Name', value: `${this.config.name}-${store.id}` }],
        });
        // Deleting the stack must not delete the database. Deletion protection alone
        // would not do it — it would fail the stack deletion instead of releasing the
        // cluster, which is a worse outcome than an orphan.
        cluster.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

        // The two endpoint attributes are different hostnames, and the certificate the
        // server presents is cut for whichever one is correct — see
        // references/analysis/egress.md#3-the-endpoint-the-task-connects-to.
        this.recordParameter(
          store.endpointParameter,
          this.config.egress === 'none' ? cluster.attrVpcEndpoint : cluster.attrEndpoint,
        );

        return {
          store,
          clusterArn: cluster.attrResourceArn,
          endpointServiceName:
            this.config.egress === 'none' ? cluster.attrVpcEndpointServiceName : undefined,
          // Always the public attribute, regardless of `egress` — see the field's
          // doc comment on IamAuthDatastoreRefs.
          publicEndpoint: cluster.attrEndpoint,
        };
      }

      return {
        store,
        clusterArn: cdk.Arn.format(
          { service: 'dsql', resource: 'cluster', resourceName: store.clusterIdentifier },
          this,
        ),
        endpointServiceName: this.config.egress === 'none' ? store.vpcEndpointServiceName : undefined,
        // No CfnCluster construct to read an attribute off — an adopted cluster's
        // public endpoint follows DSQL's fixed hostname format.
        publicEndpoint: `${store.clusterIdentifier}.dsql.${this.region}.on.aws`,
      };
    });
  }

  private buildExecutionRole(): iam.IRole {
    const role = new iam.Role(this, 'ExecutionRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: `Pulls the image and injects secrets for ${this.config.name}`,
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonECSTaskExecutionRolePolicy'),
      ],
    });

    // Secrets are injected by the ECS agent before the container starts, so this is
    // the *execution* role's job, not the task role's. Granting the task role
    // instead produces a task that fails to start, naming a role that looks right.
    const secretArns = this.config.secrets.filter((s) => s.source === 'secretsmanager').map((s) => s.arn);
    if (secretArns.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          actions: ['secretsmanager:GetSecretValue'],
          resources: secretArns,
        }),
      );
    }

    const parameterNames = this.config.secrets.filter((s) => s.source === 'ssm').map((s) => s.arn);
    if (parameterNames.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          actions: ['ssm:GetParameters'],
          resources: parameterNames.map((name) =>
            name.startsWith('arn:')
              ? name
              : cdk.Arn.format({ service: 'ssm', resource: 'parameter', resourceName: name.replace(/^\//, '') }, this),
          ),
        }),
      );
    }

    const kmsKeys = [...new Set(this.config.secrets.map((s) => s.kmsKeyArn).filter(Boolean))] as string[];
    if (kmsKeys.length > 0) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({ actions: ['kms:Decrypt'], resources: kmsKeys }),
      );
    }

    return role;
  }

  /**
   * Build every API-reached datastore the plan creates, and return the ARNs each grant
   * has to be written against.
   *
   * Created and adopted converge here deliberately: the *policy* is the same statement
   * in both cases, carrying exactly the actions the analysis recorded. Only the source
   * of the ARN differs — an adopted store names it, a created one has none until the
   * construct exists. Writing one statement shape for both keeps "never wildcards" a
   * single rule rather than two that can drift apart.
   */
  private buildApiDatastores(): Array<{ id: string; actions: string[]; resourceArns: string[] }> {
    return this.config.apiDatastores.map((store) => {
      if (store.mode === 'adopt') {
        return { id: store.id, actions: store.actions, resourceArns: store.resourceArns };
      }
      return {
        id: store.id,
        actions: store.actions,
        resourceArns: this.buildCreatedApiDatastore(store),
      };
    });
  }

  /** One created API-reached resource. All are retained: the data outlives the service. */
  private buildCreatedApiDatastore(store: CreatedApiDatastore & { id: string }): string[] {
    const id = pascal(store.id);

    switch (store.kind) {
      case 'dynamodb': {
        const table = new dynamodb.Table(this, `Datastore${id}`, {
          partitionKey: tableAttribute(store.partitionKey),
          sortKey: store.sortKey ? tableAttribute(store.sortKey) : undefined,
          // On-demand, because no capacity figure is derivable from static analysis and
          // a guessed provisioned capacity is either a throttle or a standing bill.
          billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
          // Cheap, and the alternative to having it is silent, unrecoverable data loss.
          pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
          removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        for (const index of store.indexes ?? []) {
          table.addGlobalSecondaryIndex({
            indexName: index.name,
            partitionKey: tableAttribute(index.partitionKey),
            sortKey: index.sortKey ? tableAttribute(index.sortKey) : undefined,
          });
        }

        this.recordParameter(store.attributeParameter, table.tableName);
        // The index wildcard covers the indexes *of this table* only — it is not a
        // wildcard resource, and index access genuinely needs its own ARN alongside
        // the table's, which is a routine source of confusing access-denied errors.
        return store.indexes?.length
          ? [table.tableArn, `${table.tableArn}/index/*`]
          : [table.tableArn];
      }

      case 's3': {
        const bucket = new s3.Bucket(this, `Datastore${id}`, {
          encryption: s3.BucketEncryption.S3_MANAGED,
          blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
          enforceSSL: true,
          versioned: true,
          removalPolicy: cdk.RemovalPolicy.RETAIN,
        });
        this.recordParameter(store.attributeParameter, bucket.bucketName);
        // Object actions and bucket actions take different resource ARNs. Granting only
        // the first is why `s3:ListBucket` fails on a policy that looks complete.
        return [bucket.bucketArn, `${bucket.bucketArn}/*`];
      }

      case 'sqs': {
        // A queue with no dead-letter queue silently discards what it cannot process.
        const dlq = new sqs.Queue(this, `Datastore${id}Dlq`, {
          enforceSSL: true,
          retentionPeriod: cdk.Duration.days(14),
        });
        dlq.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

        const queue = new sqs.Queue(this, `Datastore${id}`, {
          enforceSSL: true,
          deadLetterQueue: { queue: dlq, maxReceiveCount: 5 },
        });
        queue.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

        this.recordParameter(store.attributeParameter, queue.queueUrl);
        return [queue.queueArn];
      }

      case 'sns': {
        const topic = new sns.Topic(this, `Datastore${id}`, {
          displayName: `${store.id} for ${this.config.name}`,
        });
        topic.applyRemovalPolicy(cdk.RemovalPolicy.RETAIN);

        this.recordParameter(store.attributeParameter, topic.topicArn);
        return [topic.topicArn];
      }
    }
  }

  /**
   * The task role carries only what the application code was found to use, scoped to
   * the exact resources in the plan. Wildcards would make the analysis's uncertainty
   * permanent and invisible.
   */
  private buildTaskRole(
    datastores: Array<{ id: string; actions: string[]; resourceArns: string[] }>,
  ): iam.IRole {
    const role = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
      description: `Application permissions for ${this.config.name}`,
    });

    for (const store of datastores) {
      role.addToPrincipalPolicy(
        new iam.PolicyStatement({
          sid: `${pascal(store.id)}Access`,
          actions: store.actions,
          resources: store.resourceArns,
        }),
      );
    }

    return role;
  }

  // ------------------------------------------------------------------- ingress

  /**
   * The target group lives here, not in the service stack, precisely because it
   * holds the health check configuration — putting it in the service stack would
   * mean every routine deploy replaced the target group and its listener rule.
   */
  private buildLoadBalancing(vpc: ec2.IVpc, taskSg: ec2.SecurityGroup): elbv2.IApplicationTargetGroup {
    const lbConfig = this.config.loadBalancer!;
    const internetFacing = this.config.publicHostname !== undefined;

    let listener: elbv2.IApplicationListener;
    let albSecurityGroup: ec2.ISecurityGroup;

    if (lbConfig.mode === 'adopt') {
      albSecurityGroup = ec2.SecurityGroup.fromSecurityGroupId(
        this,
        'AlbSecurityGroup',
        lbConfig.securityGroupId,
      );
      listener = elbv2.ApplicationListener.fromApplicationListenerAttributes(this, 'Listener', {
        listenerArn: lbConfig.listenerArn,
        securityGroup: albSecurityGroup,
      });
    } else {
      const alb = new elbv2.ApplicationLoadBalancer(this, 'LoadBalancer', {
        vpc,
        internetFacing,
        vpcSubnets: internetFacing ? { subnetType: ec2.SubnetType.PUBLIC } : this.appSubnets,
      });
      albSecurityGroup = alb.connections.securityGroups[0];

      if (this.config.publicHostname) {
        // Imported once and shared. The zone is needed twice — to validate a created
        // certificate and to hold the alias record — and importing it under two
        // construct IDs would read as two zones in the tree.
        const zone = this.importHostedZone();
        listener = alb.addListener('HttpsListener', {
          port: 443,
          certificates: [this.buildCertificate(zone)],
          open: true,
        });
        // Redirect rather than serving plaintext on 80.
        alb.addListener('HttpRedirect', {
          port: 80,
          open: true,
          defaultAction: elbv2.ListenerAction.redirect({ protocol: 'HTTPS', port: '443', permanent: true }),
        });
        this.buildDnsRecord(alb, zone);
      } else {
        listener = alb.addListener('HttpListener', { port: 80, open: true });
      }
    }

    // Both directions have to be wired explicitly here.
    //
    // Normally CDK adds the load balancer's *egress* rule as a side effect of
    // registering a target. This design registers the target in the service stack
    // instead, so that never happens — and the result is a service whose tasks start
    // cleanly, fail every health check, and get SIGKILLed with exit code 137. The
    // logs show the app listening happily, which makes it look like an application
    // problem rather than a missing security group rule.
    //
    // EC2 restricts rule descriptions to `a-zA-Z0-9. _-:/()#,@[]+=&;{}!$*` — no
    // arrows, no angle brackets. That only fails at the API; synth and cfn-lint
    // both accept them.
    const containerPort = ec2.Port.tcp(this.config.containerPort);

    // Tasks accept traffic from the load balancer only — never from a CIDR.
    taskSg.addIngressRule(albSecurityGroup, containerPort, 'Load balancer to tasks');

    if (lbConfig.mode === 'create') {
      albSecurityGroup.addEgressRule(taskSg, containerPort, 'Load balancer to tasks');
    } else {
      // An imported security group is immutable, so the rule cannot be added here.
      cdk.Annotations.of(this).addWarningV2(
        'ecs-auto-mode:adopted-alb-egress',
        `The adopted load balancer's security group (${lbConfig.securityGroupId}) must allow ` +
          `egress to the task security group on port ${this.config.containerPort}. ` +
          'Without it, health checks fail and tasks are killed with exit code 137.',
      );
    }

    const health = this.config.healthCheck;
    const targetGroup = new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      vpc,
      port: this.config.containerPort,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targetType: elbv2.TargetType.IP,
      deregistrationDelay: cdk.Duration.seconds(30),
      healthCheck:
        health.type === 'http'
          ? {
              path: health.path,
              healthyThresholdCount: health.healthyThresholdCount ?? 2,
              interval: cdk.Duration.seconds(health.interval ?? 30),
            }
          : {
              // A TCP check: the target group still connects, it just doesn't
              // expect an HTTP response.
              protocol: elbv2.Protocol.TCP,
              healthyThresholdCount: health.healthyThresholdCount ?? 2,
              interval: cdk.Duration.seconds(health.interval ?? 30),
            },
    });

    // An adopted listener is shared, so routing needs a condition — without one it
    // either fails to attach or takes over another service's traffic.
    if (lbConfig.mode === 'adopt' && lbConfig.listenerRuleHostHeader) {
      new elbv2.ApplicationListenerRule(this, 'ListenerRule', {
        listener,
        priority: 100,
        conditions: [elbv2.ListenerCondition.hostHeaders([lbConfig.listenerRuleHostHeader])],
        targetGroups: [targetGroup],
      });
    } else if (lbConfig.mode === 'create') {
      listener.addTargetGroups('Default', { targetGroups: [targetGroup] });
    }

    return targetGroup;
  }

  /**
   * Attributes, never `fromLookup` — synth must work without credentials. The zone is
   * always adopted: creating one means delegating nameservers at a registrar, which is
   * outside what this tool can verify.
   */
  private importHostedZone(): route53.IHostedZone {
    const { hostedZoneId, zoneName } = this.config.publicHostname!;
    return route53.HostedZone.fromHostedZoneAttributes(this, 'HostedZone', {
      hostedZoneId,
      zoneName,
    });
  }

  /**
   * Created DNS-validated, or imported by ARN.
   *
   * On the create path CloudFormation's own ACM resource writes the validation record
   * into the zone and waits for issuance, so no custom resource and no extra IAM are
   * involved. The cost is that the platform stack's first deploy blocks until ACM
   * issues — and if the zone is not the one actually serving the hostname, it blocks
   * until the stack times out rather than failing fast. Planning checks the hostname
   * against the zone name for exactly that reason.
   */
  private buildCertificate(zone: route53.IHostedZone): acm.ICertificate {
    const { hostname, certificate } = this.config.publicHostname!;

    if (certificate.mode === 'adopt') {
      return acm.Certificate.fromCertificateArn(this, 'Certificate', certificate.certificateArn);
    }

    return new acm.Certificate(this, 'Certificate', {
      domainName: hostname,
      validation: acm.CertificateValidation.fromDns(zone),
    });
  }

  private buildDnsRecord(alb: elbv2.ApplicationLoadBalancer, zone: route53.IHostedZone): void {
    const { hostname } = this.config.publicHostname!;
    new route53.ARecord(this, 'AliasRecord', {
      zone,
      recordName: hostname,
      target: route53.RecordTarget.fromAlias(new targets.LoadBalancerTarget(alb)),
    });
  }

  // ------------------------------------------------------------- pipeline OIDC

  /**
   * Wired only for the github-actions pipeline target — CodePipeline authenticates
   * through a CodeStar connection instead and needs no OIDC role. Previously this
   * wiring lived outside the shipped templates entirely, hand-authored per app,
   * which is how a hardcoded bootstrap qualifier and a non-EMU trust pattern each
   * shipped without a template to diverge from.
   */
  private buildGitHubOidcRole(refs: { taskRole: iam.IRole; executionRole: iam.IRole }): void {
    if (!this.githubActions) return;

    new GitHubOidcRole(this, 'GitHubOidcRole', {
      appName: this.config.name,
      account: this.account,
      region: this.region,
      ssmPrefix: this.config.ssmPrefix,
      cdkQualifier: this.config.cdkQualifier,
      repositoryArn: this.repository.repositoryArn,
      clusterName: this.cluster.clusterName,
      taskRoleArn: refs.taskRole.roleArn,
      executionRoleArn: refs.executionRole.roleArn,
      repository: this.githubActions.repository,
      branch: this.githubActions.branch,
      existingProviderArn: this.githubActions.existingProviderArn,
    });
  }

  // ---------------------------------------------------- platform → service SSM

  /**
   * The contract with the service stack. SSM rather than CloudFormation exports, so
   * the two stacks deploy on completely independent cadences and the service stack
   * can deploy in a pipeline that has never synthesized this one.
   */
  private publishParameters(refs: {
    logGroup: logs.ILogGroup;
    taskSecurityGroup: ec2.ISecurityGroup;
    executionRole: iam.IRole;
    taskRole: iam.IRole;
    targetGroup?: elbv2.IApplicationTargetGroup;
  }): void {
    const prefix = this.config.ssmPrefix;

    const put = (name: string, value: string) => {
      new ssm.StringParameter(this, `Param${pascal(name)}`, {
        parameterName: `${prefix}/${name}`,
        stringValue: value,
      });
    };

    put('cluster-name', this.cluster.clusterName);
    put('cluster-arn', this.cluster.clusterArn);
    put('vpc-id', this.vpc.vpcId);
    put('subnet-ids', this.vpc.selectSubnets(this.appSubnets).subnetIds.join(','));
    put('task-security-group-id', refs.taskSecurityGroup.securityGroupId);
    put('repository-uri', this.repository.repositoryUri);
    put('repository-arn', this.repository.repositoryArn);
    put('log-group-name', refs.logGroup.logGroupName);
    put('execution-role-arn', refs.executionRole.roleArn);
    put('task-role-arn', refs.taskRole.roleArn);

    if (refs.targetGroup) {
      put('target-group-arn', refs.targetGroup.targetGroupArn);
    }

    // Created datastore attributes: endpoints, ports, table and bucket names, queue
    // URLs, topic ARNs, and the ARN of a created database's generated secret. Every
    // one of these is a deploy-time value, which is exactly why they travel this way
    // rather than as literals in the generated config.
    //
    // Nothing is published for an *adopted* datastore. Its identifiers were known at
    // planning time and are already literals in the config, so publishing them would
    // make this parameter set a dump of what is known rather than a contract for what
    // is not.
    for (const [suffix, value] of this.datastoreParameters) {
      put(suffix, value);
    }
  }
}

/** The RDS engine and version, as the CDK's per-engine factory wants them. */
function databaseEngine(
  engine: 'postgres' | 'mysql' | 'mariadb' | 'sqlserver' | 'oracle',
  version: string,
): rds.IInstanceEngine {
  // The CDK wants the major version alongside the full one, and derives nothing from
  // the string itself. For Postgres the major version is the first component; for the
  // others it is the first two, which is why this is not one shared expression.
  const parts = version.split('.');
  switch (engine) {
    case 'postgres':
      return rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.of(version, parts[0]),
      });
    case 'mysql':
      return rds.DatabaseInstanceEngine.mysql({
        version: rds.MysqlEngineVersion.of(version, parts.slice(0, 2).join('.')),
      });
    case 'mariadb':
      return rds.DatabaseInstanceEngine.mariaDb({
        version: rds.MariaDbEngineVersion.of(version, parts.slice(0, 2).join('.')),
      });
    case 'sqlserver':
      // Express edition: it is the one with no licence cost. A different edition is a
      // licensing decision, which is not something to infer from application code.
      return rds.DatabaseInstanceEngine.sqlServerEx({
        version: rds.SqlServerEngineVersion.of(version, parts.slice(0, 2).join('.')),
      });
    case 'oracle':
      return rds.DatabaseInstanceEngine.oracleSe2({
        version: rds.OracleEngineVersion.of(version, parts[0]),
      });
  }
}

/**
 * Whether the engine accepts a database name on the instance itself.
 *
 * SQL Server and Oracle do not — CloudFormation rejects the property, and a database
 * is created inside the instance afterwards instead.
 */
function acceptsDatabaseName(engine: string): boolean {
  return engine === 'postgres' || engine === 'mysql' || engine === 'mariadb';
}

/** A database name derived from the app name: identifiers, not hyphens. */
function databaseName(appName: string): string {
  return appName.replace(/[^a-zA-Z0-9]/g, '_');
}

function tableAttribute(attribute: TableAttribute): dynamodb.Attribute {
  const types = {
    string: dynamodb.AttributeType.STRING,
    number: dynamodb.AttributeType.NUMBER,
    binary: dynamodb.AttributeType.BINARY,
  };
  return { name: attribute.name, type: types[attribute.type] };
}

function pascal(value: string): string {
  return value.replace(/(^|[-_/])([a-z0-9])/g, (_m, _sep, ch: string) => ch.toUpperCase());
}

function retentionDays(days: number): logs.RetentionDays {
  const byValue = Object.entries(logs.RetentionDays).find(([, v]) => v === days);
  return (byValue?.[1] as logs.RetentionDays) ?? logs.RetentionDays.ONE_MONTH;
}
