// GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
// Controlled by: analysis.container, analysis.config, analysis.egress
//
// The service stack. This is what a routine deploy touches, so it contains the task
// definition and the service and nothing else — no VPC, no cluster, no registry, no
// load balancer, no IAM roles. Those live in the platform stack.
//
// Everything it needs from the platform stack is read from SSM Parameter Store, not
// from CloudFormation exports. That is what lets this deploy in a pipeline that has
// never synthesized the platform stack.

import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { AppConfig } from './config';

export interface ServiceStackProps extends cdk.StackProps {
  readonly config: AppConfig;
}

export class ServiceStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: ServiceStackProps) {
    super(scope, id, props);
    const { config } = props;
    const prefix = config.ssmPrefix;

    // The image tag is a stack parameter set by the pipeline to the commit SHA.
    // A mutable tag like `latest` would leave this template byte-identical between
    // deploys, so CloudFormation would see no change and the rollout would not happen.
    const imageTag = new cdk.CfnParameter(this, 'ImageTag', {
      type: 'String',
      description: 'Immutable image tag to deploy — the commit SHA, never `latest`',
      minLength: 1,
    });

    // Resolved at deploy time from parameters the platform stack published.
    const read = (name: string) =>
      ssm.StringParameter.valueForStringParameter(this, `${prefix}/${name}`);

    const clusterName = read('cluster-name');
    const vpcId = read('vpc-id');
    const subnetIds = cdk.Fn.split(',', read('subnet-ids'));
    const taskSecurityGroupId = read('task-security-group-id');
    const repositoryArn = read('repository-arn');
    const logGroupName = read('log-group-name');
    const executionRoleArn = read('execution-role-arn');
    const taskRoleArn = read('task-role-arn');

    // FargateService reads `cluster.vpc` during construction even though placement
    // comes from the explicit `vpcSubnets` below, and `fromClusterArn` produces a
    // cluster with no VPC — so the VPC has to be imported here. It contributes
    // nothing to the synthesized template, which is why cfn-lint reports the
    // vpc-id parameter as unused (W2001). That warning is expected.
    const vpc = ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
      vpcId,
      availabilityZones: cdk.Fn.getAzs(),
    });
    cdk.Annotations.of(vpc).acknowledgeWarning(
      '@aws-cdk/aws-ec2:vpcAttributeIsListTokenavailabilityZones',
      'AZs are unused here; placement comes from the SSM-published subnet IDs',
    );

    const cluster = ecs.Cluster.fromClusterAttributes(this, 'Cluster', {
      clusterName,
      vpc,
      securityGroups: [],
    });

    const taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
      cpu: config.sizing.cpu,
      memoryLimitMiB: config.sizing.memoryLimitMiB,
      // Must match the architecture the image was built for. A mismatch produces an
      // exec-format error whose cause is not obvious from the message.
      runtimePlatform: {
        cpuArchitecture:
          config.architecture === 'ARM64'
            ? ecs.CpuArchitecture.ARM64
            : ecs.CpuArchitecture.X86_64,
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
      },
      executionRole: iam.Role.fromRoleArn(this, 'ExecutionRole', executionRoleArn, {
        mutable: false,
      }),
      taskRole: iam.Role.fromRoleArn(this, 'TaskRole', taskRoleArn, { mutable: false }),
    });

    const repository = ecr.Repository.fromRepositoryAttributes(this, 'Repository', {
      repositoryArn,
      repositoryName: config.name,
    });

    const container = taskDefinition.addContainer('app', {
      image: ecs.ContainerImage.fromEcrRepository(repository, imageTag.valueAsString),
      environment: this.buildEnvironment(config, read),
      secrets: this.buildSecrets(config, read),
      logging: ecs.LogDrivers.awsLogs({
        streamPrefix: config.name,
        logGroup: logs.LogGroup.fromLogGroupName(this, 'LogGroup', logGroupName),
      }),
      // Surfaces a non-zero exit as a stopped-task reason rather than a silent restart.
      essential: true,
    });

    container.addPortMappings({
      containerPort: config.containerPort,
      protocol: ecs.Protocol.TCP,
    });

    const service = new ecs.FargateService(this, 'Service', {
      cluster,
      taskDefinition,
      // Deterministic name: deploy-permissions.ts's EcsService IAM grant and the
      // pipeline's "wait for steady state" step both address the service by
      // <app.name> directly. Leaving this to the CloudFormation default produces a
      // generated physical name that matches neither.
      serviceName: config.name,
      desiredCount: config.sizing.desiredCount,
      assignPublicIp: false,
      securityGroups: [
        ec2.SecurityGroup.fromSecurityGroupId(this, 'TaskSecurityGroup', taskSecurityGroupId),
      ],
      vpcSubnets: {
        subnets: subnetIds.map((id, i) => {
          const subnet = ec2.Subnet.fromSubnetId(this, `Subnet${i}`, id);
          // Route tables are never consulted here — placement is all this needs.
          cdk.Annotations.of(subnet).acknowledgeWarning(
            '@aws-cdk/aws-ec2:noSubnetRouteTableId',
            'Subnets are used for task placement only; route tables belong to the platform stack',
          );
          return subnet;
        }),
      },
      circuitBreaker: { rollback: true },
      minHealthyPercent: 100,
    });

    // `cdk synth` emits template-validation WARNINGs for this stack — subnet IDs,
    // role ARNs and the log group name "do not match expected format". They are
    // false positives and are expected: the linter evaluates each SSM parameter's
    // *default*, which is the parameter path, while CloudFormation resolves the real
    // value at deploy time. They cannot be suppressed per-rule, so they are
    // documented in the generated README instead of hidden.

    if (config.loadBalancer) {
      // The target group itself lives in the platform stack — it holds the health
      // check config, and recreating it on every deploy would churn the listener rule.
      const targetGroup = elbv2.ApplicationTargetGroup.fromTargetGroupAttributes(
        this,
        'TargetGroup',
        { targetGroupArn: read('target-group-arn') },
      );
      service.attachToApplicationTargetGroup(targetGroup);
      // Expected: the platform stack already opened the task security group to the
      // load balancer's, so there is no connectable wiring left for this stack to do.
      cdk.Annotations.of(targetGroup).acknowledgeWarning(
        '@aws-cdk/aws-elbv2:albTargetGroupCannotRegisterConnectable',
        'Task security group ingress from the ALB is created in the platform stack',
      );
    }

    new cdk.CfnOutput(this, 'DeployedImageTag', { value: imageTag.valueAsString });
  }

  /**
   * Environment variables, from two sources that cannot be one.
   *
   * `environment` holds literals — values known when the plan was approved, which is
   * every adopted resource's name. `environmentFromSsm` holds the ones that were not:
   * a *created* table's name, a created cache's endpoint. Those are deploy-time values,
   * so they arrive as parameters the platform stack published.
   *
   * A name appearing in both is an error rather than a precedence question. Silently
   * preferring one would leave the container reading a value the plan does not show,
   * which is the kind of thing that is only ever diagnosed by reading a task definition
   * in the console.
   */
  private buildEnvironment(
    config: AppConfig,
    read: (name: string) => string,
  ): Record<string, string> {
    const environment: Record<string, string> = { ...config.environment };

    for (const [name, parameter] of Object.entries(config.environmentFromSsm)) {
      if (name in environment) {
        throw new Error(
          `environment variable ${name} is set both as a literal and from the SSM parameter ${parameter} — one would silently win`,
        );
      }
      environment[name] = read(parameter);
    }

    const clash = Object.keys(environment).filter((name) => secretNames(config).has(name));
    if (clash.length > 0) {
      throw new Error(
        `environment variable(s) ${clash.join(', ')} are set as both an environment value and a secret — ECS rejects a task definition that does both`,
      );
    }

    return environment;
  }

  /**
   * Secrets are injected by reference. No value passes through this template — the
   * ECS agent fetches them at task start using the execution role.
   *
   * Two sources, and the difference is who owns the secret. `config.secrets` are
   * secrets that already existed and were named in the plan. A *created* database's
   * credentials are generated, so nothing could name them at planning time: the
   * platform stack makes the secret, grants the execution role read on it, and
   * publishes its ARN, and each mapped field is injected from there.
   */
  private buildSecrets(
    config: AppConfig,
    read: (name: string) => string,
  ): Record<string, ecs.Secret> {
    const secrets: Record<string, ecs.Secret> = {};

    for (const store of config.networkDatastores) {
      if (store.mode !== 'create') continue;
      if (store.kind !== 'rds' && store.kind !== 'documentdb') continue;

      // `fromSecretCompleteArn` takes an unresolved token: it stores the ARN without
      // parsing it, and `ecs.Secret.fromSecretsManager` appends `:<field>::` to build
      // the `valueFrom`. That is what makes reading the ARN from SSM viable, and why
      // the alternative — a partial ARN from `fromSecretNameV2`, which would need a
      // wildcard on the execution role's grant — is not used.
      const secret = secretsmanager.Secret.fromSecretCompleteArn(
        this,
        `DatastoreSecret${store.id}`,
        read(store.credentials.secretArnParameter),
      );

      for (const [name, field] of Object.entries(store.credentials.fields)) {
        if (name in secrets) {
          throw new Error(`environment variable ${name} is injected by more than one datastore secret`);
        }
        secrets[name] = ecs.Secret.fromSecretsManager(secret, field);
      }
    }

    for (const ref of config.secrets) {
      if (ref.name in secrets) {
        throw new Error(
          `secret ${ref.name} is recorded in the plan and also supplied by a created datastore's generated credentials — the plan should record one source, not both`,
        );
      }
      if (ref.source === 'secretsmanager') {
        const secret = secretsmanager.Secret.fromSecretCompleteArn(
          this,
          `Secret${ref.name}`,
          ref.arn,
        );
        secrets[ref.name] = ref.jsonKey
          ? ecs.Secret.fromSecretsManager(secret, ref.jsonKey)
          : ecs.Secret.fromSecretsManager(secret);
      } else {
        const parameter = ssm.StringParameter.fromSecureStringParameterAttributes(
          this,
          `Parameter${ref.name}`,
          { parameterName: ref.arn },
        );
        secrets[ref.name] = ecs.Secret.fromSsmParameter(parameter);
      }
    }

    return secrets;
  }
}

/** Every environment variable name that arrives as a secret rather than a value. */
function secretNames(config: AppConfig): Set<string> {
  const names = new Set(config.secrets.map((ref) => ref.name));
  for (const store of config.networkDatastores) {
    if (store.mode !== 'create') continue;
    if (store.kind !== 'rds' && store.kind !== 'documentdb') continue;
    for (const name of Object.keys(store.credentials.fields)) names.add(name);
  }
  return names;
}
