#!/usr/bin/env bash
# GENERATED by ecs-truly-auto-mode from .ecs-auto-mode/manifest.yaml
# Controlled by: target.ssmPrefix
#
# Asserts that every SSM parameter the service stack reads exists before the deploy
# is attempted.
#
# This is the guard on the one weakness of coupling the two stacks through SSM rather
# than CloudFormation exports: the decoupling that lets them deploy independently is
# the same decoupling that lets the service stack be deployed against a platform
# stack that was never deployed, or that has changed underneath it.
#
# Without this check the failure still happens, but it surfaces as a CloudFormation
# error about an unresolvable SSM reference partway through a deploy — considerably
# harder to act on than a named missing parameter before anything has changed.

set -euo pipefail

PREFIX="${1:?usage: ssm-preflight.sh <ssm-prefix> <region> [--load-balanced]}"
REGION="${2:?usage: ssm-preflight.sh <ssm-prefix> <region> [--load-balanced]}"
LOAD_BALANCED="${3:-}"

REQUIRED=(
  cluster-name
  vpc-id
  subnet-ids
  task-security-group-id
  repository-uri
  repository-arn
  log-group-name
  execution-role-arn
  task-role-arn
)

if [ "$LOAD_BALANCED" = "--load-balanced" ]; then
  REQUIRED+=(target-group-arn)
fi

echo "Preflight: checking ${#REQUIRED[@]} parameters under ${PREFIX} in ${REGION}"

# One call for all of them. get-parameters reports unknown names in InvalidParameters
# rather than failing, which is exactly the shape needed to name what is missing.
NAMES=()
for name in "${REQUIRED[@]}"; do
  NAMES+=("${PREFIX}/${name}")
done

INVALID="$(aws ssm get-parameters \
  --names "${NAMES[@]}" \
  --region "$REGION" \
  --query 'InvalidParameters' \
  --output text)"

if [ -n "$INVALID" ] && [ "$INVALID" != "None" ]; then
  echo ""
  echo "Preflight FAILED — these parameters do not exist:"
  for param in $INVALID; do
    echo "  $param"
  done
  echo ""
  echo "The platform stack publishes these. Either it has not been deployed to"
  echo "${REGION}, or it was deployed with a different ssmPrefix."
  echo ""
  echo "  cd infra && npx cdk deploy <app>-platform"
  echo ""
  exit 1
fi

echo "Preflight OK — all parameters present."
